### ISSUE TITLE
opt viewer popup bolds text between libc++ __1 inline namespaces

### ISSUE THREAD

**Issue by aw1621107** [mattgodbolt/compiler-explorer#1005]
Example:

![bold](https://user-images.githubusercontent.com/566572/42820993-7d5487ba-89a5-11e8-87f8-27fe4ac1df3d.png)

**Comment by RabsRincon** [comment]
Hi @aw1621107, thanks for the report, and sorry! This should have not taken so long get an answer! 

This bug is not something we can fix, as there currently seems not to be a way to disable markup detection on bits of the hover message on the Monaco editor, which is the main reason why this happens

Sorry again for the delayed response.
