### ISSUE TITLE
Drop-down menu options in compiler pane do not work on android chrome

### ISSUE THREAD

**Issue by steveire** [mattgodbolt/compiler-explorer#1152]
On my android phone with chrome, I can visit godbolt.org and if I try to select any option from the compiler drop-down menu (eg to create a clang-tidy tool), it does not work. The menu appears, but pressing the option (or any other option in the menu) does not work.

**Comment by RabsRincon** [comment]
Hi! Sorry you have had to experience our poor mobile experience, but saddly we can't do anything with it (Yet! We might have something eventually!) because most of the components (The editor being the most prominent one) are not mobile friendly. I'll close this one in favour of #176 


Let us know if we can help you with something else! :)
