### ISSUE TITLE
"Filter Unused Labels" removes some labels that are used

### ISSUE THREAD

**Issue by josephcsible** [mattgodbolt/compiler-explorer#1179]
Consider this C program:
```c
#include <stdio.h>

extern void *my_own_address;

__asm__(
    "my_own_address:\n"
    ".quad .\n"
);

int main(void) {
    printf("%p %p\n", &my_own_address, my_own_address);
    return 0;
}
```

When compiling with x86-64 clang 7.0.0, you get this:

```asm
my_own_address:
        .quad   .Ltmp0

main:                                   # @main
# snip rest of output - irrelevant for purposes of this bug
```

Note that the `.Ltmp0` label is used, but doesn't appear. Disabling "Filter unused labels from the output" reveals it, right below `my_own_address`:

```asm
my_own_address:
.Ltmp0:
        .quad   .Ltmp0

main:                                   # @main
# snip rest of output - irrelevant for purposes of this bug
```

Link that demonstrates all this: https://godbolt.org/z/6BOQhx

**Comment by mattgodbolt** [comment]
Interesting one this! There's some nasty (and hacky) code in the "is tihs used" code. I have been long suspecting it needs a principled approach instead of the organically grown heuristics. This might be the reason to undertake that project.

...or it may be a fairly simple extra hack to layer on top of what we already have...

**Comment by mattgodbolt** [comment]
super minimal repro: https://godbolt.org/z/I41Kj4
