### ISSUE TITLE
Recompiling doesn't work when auto-compiling is off

### ISSUE THREAD

**Issue by breeswish** [mattgodbolt/compiler-explorer#1238]
First, disable auto-compiling.

Then, for example, let's type some code and add a compiler:

```rust
fn main() {
    println!("This should compile");
}
```

This will work. Then, change the source code to something doesn't compile, e.g.

```rust
fn main() {
    println!("This should not compile
}
```

And click "Clear cache and recompile". The compiling still succeed. It only compiles the source code given when clicking "Add compiler", but not latest source code.

**Comment by RabsRincon** [comment]
Hi! Thanks for looking into it @ajcarvajal , we really appreciate it. I have now locally fixed this, but ran out of time to push the changes. I'm hoping I'll get a chance tomorrow moring. Sorry for keeping all you waiting! :)

(The problem was on how we handled debouced source changes and compileOnChange settings)
