### ISSUE TITLE
Zig does not compile because of line endings

### ISSUE THREAD

**Issue by Sahnvour** [mattgodbolt/compiler-explorer#1250]
Currently, I'm not able to compile any Zig code containing line breaks (just try with the default square function), getting this compiler error: `<source>:2:33: error: invalid carriage return, only '\n' line endings are supported`.

see also https://ziglang.org/documentation/master/#Source-Encoding

**Comment by mattgodbolt** [comment]
CC @tiehuis - any ideas?

**Comment by tiehuis** [comment]
On Windows it appears Monaco gives back lines with carriage returns when asking for text from the buffer by default since we don't explicitly specify what we want.

Adding a request explicitly for newline only data from the editor should fix this, presumably at this point [here](https://github.com/mattgodbolt/compiler-explorer/blob/396a634abd4e2c82e04e5deb416ef821eca5402f/static/panes/editor.js#L197). See api documentation for [getValue](https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.itextmodel.html#getvalue).

Changing like this would be shared across all languages however, would this behavior be valid? Is there any reason to keep the status quo for any languages?

**Comment by mattgodbolt** [comment]
From @RabsRincon  (who is offline but replied in slack):

```
this.editor.getModel().setEOL(monaco.editor.EndOfLineSequence.LF);
```

plus a bit of logic should do the trick on the editor

**Comment by RabsRincon** [comment]
Ey! Sorry this took so long. I have forced a LF EOL in the editor which seems to fix the problem and not cause other languages to fail, so the fix should be pushed with the next site update :)
I missreferenced the issue in the commit message, but e326384 closes this
