### ISSUE TITLE
zig: support -emit llvm-ir to see llvm-ir

### ISSUE THREAD

**Issue by shawnl** [mattgodbolt/compiler-explorer#1328]
@tiehuis

**Comment by tiehuis** [comment]
I think this can be done entirely on the Zig side. The relevant snippet in compiler-explorer is here: https://github.com/mattgodbolt/compiler-explorer/blob/master/lib/compilers/zig.js#L62

On testing however it appears that when emitting llvm-ir with a specific output name, such as with `zig build-exe t.zig --emit llvm-ir --output-dir . --name t.s`, the generated output always appends the `.ll` suffix and actually generates a file called `t.s.ll`.

I would first change the `--name` field in zig to respect it completely and not add trailing suffixes, since this doesn't seem like the expected behavior for a user. Then, we may need to make a small adjustment here as the current compiler looks to handle the extra `.s` suffix via basename.

**Comment by emekoi** [comment]
can't we just override `getIrOutputFilename` as the rust and d compilers do?
