### ISSUE TITLE
icc 13.0.1 gives gateway timeout

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/compiler-explorer#1385]
e.g. https://godbolt.org/z/5UIn90  (gateway timeout)

On the backend:

```
May 19 14:49:50 ip-172-30-0-189 amazon:  warn: Timeout for /usr/local/bin/firejail --quiet,--profile=etc/firejail/execute.profile,--private=/tmp/compiler-explorer-compiler119419-1177-pm9oi0.uqem,/opt/compiler-explorer/intel/bin/icc,-g,-o,./output.s,-masm=intel,-S,-gxx-name=/opt/compiler-explorer/gcc-4.7.1/bin/g++,./example.cpp after 20000ms 
```

**Comment by mattgodbolt** [comment]
Confirmed locally it's `firejail` causing issues. I get "error 5" locally though.

**Comment by mattgodbolt** [comment]
Seems it's `private-tmp` that breaks it. Intriguing: I wonder what's going on here!

**Comment by mattgodbolt** [comment]
Annoyingly the process actually seems to work. I suspect some kind of intel daemon is `fork()`ed - there's a `intel/ism/` hierarchy of files created in the home directory. I wonder if some daemon process expects to be communicated with via `/tmp`.

**Comment by mattgodbolt** [comment]
running with strace outside of the firejail:

```
21412 stat("/opt/intel/ism/bin/intel64/intelremotemond",  <unfinished ...>
21401 unlink("/tmp/iccgasGRvXtr" <unfinished ...>
21412 <... stat resumed> 0x7ffddaf2b320) = -1 ENOENT (No such file or directory)
21401 <... unlink resumed> )            = 0
21412 stat("/home/matthew/intel/ism/bin/intel64/intelremotemond",  <unfinished ...>
21401 unlink("/tmp/iccldashv4vGqza" <unfinished ...>
21412 <... stat resumed> 0x7ffddaf2b320) = -1 ENOENT (No such file or directory)
21401 <... unlink resumed> )            = 0
21412 semop(294914, [{0, -1, SEM_UNDO|IPC_NOWAIT}], 1 <unfinished ...>
21401 unlink("/tmp/icctempfilejczF71" <unfinished ...>
21412 <... semop resumed> )             = 0
21412 semop(294914, [{1, -1, SEM_UNDO|IPC_NOWAIT}], 1 <unfinished ...>
21401 <... unlink resumed> )            = 0
21412 <... semop resumed> )             = 0
21401 unlink("/tmp/iccargyXnVFT" <unfinished ...>
21412 semop(294914, [{2, -1, SEM_UNDO|IPC_NOWAIT}], 1) = 0
21401 <... unlink resumed> )            = 0
21412 semop(294914, [{3, -1, SEM_UNDO|IPC_NOWAIT}], 1) = 0
21412 semop(294914, [{4, -1, SEM_UNDO|IPC_NOWAIT}], 1) = 0
21412 semctl(294914, 0, IPC_RMID, NULL) = 0
21412 exit_group(5)                     = ?
21401 exit_group(0)                     = ?
21402 <... futex resumed>)              = ?
21412 +++ exited with 5 +++
21402 +++ exited with 0 +++
21411 <... wait4 resumed> [{WIFEXITED(s) && WEXITSTATUS(s) == 5}], 0, NULL) = 21412
21411 --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=21412, si_uid=1000, si_status=5, si_utime=0, si_stime=0} ---
21411 exit_group(5)                     = ?
21401 +++ exited with 0 +++
21411 +++ exited with 5 +++
```

It seems the main process exits with 0, but one of the child processes (both the "intelremotemond" and its parent) exit with 5

**Comment by mattgodbolt** [comment]
If I run my own intelremotemond (from another install) It Just Works™. Ugh. Trying to work out how to disable it.

**Comment by mattgodbolt** [comment]
With thanks to twitter, some maybe helpful env vars:

```
ltrace -e getenv /opt/compiler-explorer/intel/bin/icc -g -o ./output.s -masm=intel -S -gxx-name=/opt/compiler-explorer/gcc-4.7.1/bin/g++ ./example.cpp 2>&1 | sort -u | cut -d\" -f 2 | sort -u | egrep '^[A-Z]+'
FLEXLM_BATCH
FLEXLM_BORROWFILE
FLEXLM_DEBUG_BADDATE
FLEXLM_DIAGNOSTICS
FLEXLM_NO_CKOUT_INSTALL_LIC
FLEXLM_RC
FLEXLM_USE_FINDER
GCCROOT
HOME
ICCCFG
IC_USE_PATH
INTEL_LICENSE_FILE
INTEL_LMD_DEBUG
LANG
L_BORROW_ERR
LC_ALL
LC_CTYPE
LM_APP_DISABLE_CACHE_READ
LM_BORROW
LM_LICENSE_FILE
NLSPATH
TEMP
TMP
TMPDIR
Vxq2Rfw2442332332332XWF25345
```

**Comment by apmorton** [comment]
wonder if it may be worth it to have a small wrapper process inside firejail that catches all forks and kills them when the main child exits?

**Comment by mattgodbolt** [comment]
Enabling shell has seemingly "fixed" it locally. This seems...unlikely. But I'm going with it for now :/

**Comment by mattgodbolt** [comment]
Ah no -- it's actually random! ARG. Seems whichever process exits last out of the jail is what firejail returns as the exit code. That means if the `fork()`ed, failing intelremotemond happens to exit last, its failing return code is the one returned. The shell thing seems to just make it more likely that the compiler exits last, but it isn't infallible.

**Comment by apmorton** [comment]
https://github.com/netblue30/firejail/blob/master/src/firejail/sandbox.c#L325

there is even a special case in firejail for an application that forks a child that must be killed with a todo note about making this generic.

having firejail not deterministically return the original child processes exit status is also a result of this mechanism.

Firejail handles child terminations until it sees the "monitored_pid" terminate, which initially is the forked child firejail creates.

It then scans /proc for any remaining pids and chooses one to be the new "monitored_pid".

Seems like having two options added to firejail could fix these kinds of issues across the board. (although mitigating them on a case by case basis may still be worth it over time, to cut down on wasted cpu cycles).

- always exit firejail with the originally forked childs exit code
- sigterm all remaining processes once the originally forked child exits

**Comment by apmorton** [comment]
See if this firejail patch helps at all.
If it proves useful I will try to come up with a less obnoxious flag than `--deterministic-exit-code`, look into adding these options to the profile file parser so they don't clutter up the command line, and submit a PR upstream.

https://github.com/apmorton/firejail/commit/7de5c1ef558c2d3eacd012729bbe622ca5362519

Patch tested as follows:

file `test.sh` creates some double forked children that delay and each return a unique exit code
```bash
#!/bin/bash

echo "starting orphans"
{ nohup bash -c "sleep 2; exit 1" &> /dev/null & } &
{ nohup bash -c "sleep 2; exit 2" &> /dev/null & } &
{ nohup bash -c "sleep 2; exit 3" &> /dev/null & } &

echo "sleeping 0.5 seconds"
sleep 0.5

echo "main application exiting"
exit 4

```

## existing behavior
`firejail --noprofile --quiet ./test.sh; echo status $?`
- will block until all orphaned children naturally exit
- will exit with code 1, 2, or 3 randomly
  - although it heavily favors exit code 3 in this example, since it is the last sleep to be started

## with deterministic exit code
`firejail --noprofile --deterministic-exit-code --quiet ./test.sh; echo status $?`
- will block until all orphaned children naturally exit
- will exit with code 4
  - exit codes of other children are swallowed

## with terminate orphans
`firejail --noprofile --terminate-orphans --quiet ./test.sh; echo status $?`
- sigterm all remaining children and wait for them to naturally exit
  - does not send sigkill, so misbehaving children will cause a hang
- will exit with code 255 (from firejail itself)

## with both
`firejail --noprofile --terminate-orphans --deterministic-exit-code --quiet ./test.sh; echo status $?`
- sigterm all remaining children and wait for them to naturally exit
  - does not send sigkill, so misbehaving children will cause a hang
- will exit with code 4

**Comment by mattgodbolt** [comment]
Wow, thanks @apmorton - will give this a go today. (Have other possible workarounds if needed too, but this looks great!)

**Comment by mattgodbolt** [comment]
Fixed, thanks to @apmorton :)
