### ISSUE TITLE
GCC and Clang don't link against pthread when using std::thread

### ISSUE THREAD

**Issue by bstaletic** [mattgodbolt/compiler-explorer#1428]
https://godbolt.org/z/1T6Q7V

However, adding `-pthread` results in:

```
terminate called after throwing an instance of 'std::system_error'
  what():  Resource temporarily unavailable
```

**Comment by apmorton** [comment]
Not sure what is causing `-pthread` to be required here - I cannot reproduce this on a local instance of CE using identical compiler binaries to those on godbolt.org.

`Resource temporarily unavailable` is caused by `rlimit-nproc` in `etc/firejail/sandbox.profile`

This was ultimately necessary to prevent damage from fork bombs, but due to how firejail is implemented this doesn't really do what we want.

It has the unintended effect of preventing _any_ threads or child processes from being created.

Until we switch to nsjail I don't think we have any viable fixes for this that don't open us up to fork bombs causing havoc.

**Comment by apmorton** [comment]
`-pthread` is still required to avoid linker errors, but the site now supports threads during execution.

See #1910
