### ISSUE TITLE
New library support - openssl

### ISSUE THREAD

**Issue by shreyans800755** [mattgodbolt/compiler-explorer#1471]
Support for openssl libraries would be great. Although I'm not sure how sandboxing is done to avoid running damaging command on server, since openssl may have such kind of functions.

**Comment by mattgodbolt** [comment]
We currently don't support linking against any library. All libraries are header-only. This is not out of security concerns (you can write all of OpenSSL into a single C file and compile that if you want) but because most libraries are built with a specific compiler and compiler settings and we can't support the 300x100+ matrix of "all compilers" times "all library versions" that this would often entail (and that's ignoring ABI differences like C++11 vs pre-C++11)

**Comment by partouf** [comment]
I'm sort of wondering that - if we can guarantee cdecl .so shared libraries for x86 and 64 somehow, and make the linking use dynamic linking - maybe we can support some libraries, and I think definitely OpenSSL.

It wouldn't really matter who did the building in that case.

**Comment by partouf** [comment]
OpenSSL 1.1.1c has now been added as a library that you can link to for x86 and x86_64 executables, have fun :)
