### ISSUE TITLE
[BUG] Clang-tidy is always using trunk version

### ISSUE THREAD

**Issue by JVApen** [mattgodbolt/compiler-explorer#1532]
**Describe the bug**
At the moment, it's possible to add a clang-tidy instance in compiler explorer.
However, this clang-tidy instance seems to always be the Trunk version iso the one linked to the release.

**To Reproduce**

- Create a project with clang 7.0.0
- Add tidy compiler to it
- Extends its arguments with --version

**Expected behavior**
To see LLVM 7.0.0 to be used, matching the clang-version.

**Link**
https://godbolt.org/z/5AXNdX

**Current output**
```
LLVM (http://llvm.org/):
  LLVM version 10.0.0svn
  Optimized build.
  Default target: x86_64-unknown-linux-gnu
  Host CPU: skylake-avx512
```

**Desktop (please complete the following information):**
 Not relevant

**Additional Info**
If not possible to fix this, it would be really nice if you can improve the expectations by updating the title from 'clang-tidy #1 with x86-64 clang 7.0.0' to 'clang-tidy (trunk) #1 with x86-64 clang 7.0.0'

**Comment by RabsRincon** [comment]
Hi. Thanks for the suggestion. Unfortunately your expected behaviour is not something the current setup allows :/

But! What we can do is to update the title exactly as you suggested, so there is less confusion as to which version is being used.

Thanks again for taking the time to create the issue :)
