### ISSUE TITLE
[REQUEST] Clicking or double clicking on a label in assembly should bring you to that label

### ISSUE THREAD

**Issue by pgoodman** [mattgodbolt/compiler-explorer#1563]
**Is your feature request related to a problem? Please describe.**
Assembly output often contains direct or conditional jumps to labelled code, e.g. `.LBB01` type of thing. Finding that code requires scrolling around, and lots of labels are similarly named.

**Describe the solution you'd like**
Ideally, I would like label operands in assembly instructions to be hyperlinks to the label locations.

**Describe alternatives you've considered**
The graph view can be used, though that leaves much to be desired as basic blocks will sometimes overlap, and usually you need to manually move things around a bit.

**Additional context**
This is a pretty typical feature in things interactive disassemblers and makes navigating assembly output much easier.

**Comment by partouf** [comment]
I noticed in the code that there's already a way to store the jump location in the links property (https://github.com/mattgodbolt/compiler-explorer/blob/master/lib/asm-parser.js#L461) during asm-parsing binary mode compilations, but there's not a similar mechanism in the normal assembly parsing.

We can maybe use this information in the UI to create links to the right places. And then also add a similar mechanism to normal asm parsing (although obviously different because normal assembly doesn't always contain the address in the jump but just the label).

**Comment by mattgodbolt** [comment]
See #31
