### ISSUE TITLE
[REQUEST] Binary support for assembly

### ISSUE THREAD

**Issue by shachaf** [mattgodbolt/compiler-explorer#1567]
Currently x86-64 assembly is supported as a language, but it doesn't have binary (disassembly) support. The main reason I've wanted assembly as a language before was to look at the precise instruction encoding -- translating assembly to assembly doesn't seem like what I want -- so displaying it would be a nice feature.

I've used inline assembly in C code in the past to accomplish this, but it seems a bit silly.

**Comment by partouf** [comment]
Looked at this problem, but realized that this is already happening by default (because assemblers usually only generate binaries). The only difference with regular binary mode is that the UI look is slightly different and is missing the instruction byte representation. I will try to get that to work.
