### ISSUE TITLE
[BUG] OCaml compilers disappeared

### ISSUE THREAD

**Issue by Freyr666** [mattgodbolt/compiler-explorer#1610]
OCaml 4.08 compilers are missing

Did I break something in #1608? I hope not.

**Comment by apmorton** [comment]
The OCaml builds are still manual - looks like whoever merged your PR on the image repo wasn't aware of this and didn't kick off the build.

Doing so now.

**Comment by apmorton** [comment]
@RabsRincon @partouf documenting the commands to build ocaml here for future reference

```
version=4.09.0
ce builder exec -- sudo docker run --rm --name ocaml.build -v/home/ubuntu/.s3cfg:/root/.s3cfg:ro apmorton/ocaml-builder:latest bash build.sh ${version} s3://compiler-explorer/opt/ yes
ce builder exec -- sudo docker run --rm --name ocaml.build -v/home/ubuntu/.s3cfg:/root/.s3cfg:ro apmorton/ocaml-builder:latest bash build.sh ${version}-flambda s3://compiler-explorer/opt/ yes
```

note, I am using my own `apmorton/ocaml-builder` docker image since matt's is not configured correctly. @mattgodbolt your image on dockerhub still has no tags - I think maybe there is a github integration missing here maybe since the others get updated automatically?
