### ISSUE TITLE
[REQUEST] Set the fontLigatures: true option in monaco editor config

### ISSUE THREAD

**Issue by RedBeard0531** [mattgodbolt/compiler-explorer#1653]
**Is your feature request related to a problem? Please describe.**
When opting-in to using [Fira Code](https://github.com/tonsky/FiraCode) font, I would like to see the pretty ligatures.

**Describe the solution you'd like**
Add [this setting](https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.ieditoroptions.html#fontligatures) to each of the calls to `monaco.editor.create()`, such as [here](https://github.com/mattgodbolt/compiler-explorer/blob/ef27d4efb0292f3253e440f5b389d8638b32d5dd/static/panes/editor.js#L89)

**Describe alternatives you've considered**
You could also make this a setting, but I doubt it is worth it. If someone has chosen a ligature-enabled monospace font, they probably want ligatures to show up :smile: 

**Additional context**
<img src="https://github.com/tonsky/FiraCode/raw/master/showcases/all_ligatures.png">

**Comment by RabsRincon** [comment]
Hi, thanks for the suggestion! I've now added a setting (defaults to true) to enable font ligatures :)
It should hit the live site shortly

**Comment by vincentisambart** [comment]
@RabsRincon I'm sorry but I think that that setting should default to false.
On Safari (13.0.3) on my Mac (Mojave 10.14.6) with all default settings, when typing `float`, the `fl` ligature gets used and the caret placement get strange. Probably because the `fl` ligature seems to have the same width as 1 character even though it's 2.
<img width="290" src="https://user-images.githubusercontent.com/34704/68093081-42941180-fed5-11e9-9daa-71692a59dc5a.png">
