### ISSUE TITLE
Search for base-64 short URL that isn't hard to read loops a lot

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/compiler-explorer#1706]
The system that looks for a "good" SHA for a short URL retries quite a lot: https://my.papertrailapp.com/events?q=Unusable%20text%20found

![Screenshot from 2019-11-25 16-00-02](https://user-images.githubusercontent.com/633973/69581748-aa052480-0f9c-11ea-8c35-f5dd970e12ba.png)

We might be able to avoid this in other ways (using something other than base-64, or different digits?). We would need to be super careful we didn't break anything existing.

No obvious problem with the current approach, filing only as it seemed surprising at first when I spotted it in papertrail.

**Comment by jameshamm** [comment]
(I don't really know the current system, so ignore this if it is not relevant. This is based on a skim of the code in lib/storage/storage.js)

Assuming that currently a good SHA for a short URL is one that when it is encoded in base64 it

1. Doesn't use [confusing](https://github.com/mattgodbolt/compiler-explorer/commit/2364ecac75552aa22e15d7cec3642a71b437b8db) characters (no o0 or Il1) 
2. Doesn't [contain](https://github.com/mattgodbolt/compiler-explorer/pull/1301/files) profanity.
3. Hasn't been used before.

Looking at [the loop](https://github.com/mattgodbolt/compiler-explorer/blob/4ddaac18c652411a6a7e841b2074b1105bc3cd24/lib/storage/storage.js#L71) it seems like the makes sure the first 12 characters are acceptable. (However, in a short URL from the live site I only see 6 characters, am I missing something?)
The easiest thing I can think of would be maybe allow more characters through.

Disallowing "iol01" and those letters in uppercase brings the current alphabet from "'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-_'" down to "abcdefghjkmnpqrstuvwxyzABCDEFGHJKMNPQRSTUVWXYZ23456789-_", or 64 characters down to 56. That means that 1 out of every 8 characters is disallowed. I *think* that means if you chose 12 random characters from the base64 alphabet, there is a 80% chance it will contain a disallowed character (assuming each character is equally likely). That could be the cause of the noticeable number of retries.

    sum(8/64*(56/64)**i for i in range(12))  # outputs 0.79858, ~80%

If you were to allow more characters (for example uppercase 'L') or replace some troublesome characters with others ('1' -> '~') you can increase the chances of not having a disallowed character in an encoding. If you get really stuck for letters, you could try and come up with a scheme to disambiguate some of the characters, like allowing 'i' but only if it is the first or last character in the URL.

    sum(7/64*(57/64)**i for i in range(12))  # ~75%
    sum(6/64*(58/64)**i for i in range(12))  # ~69.3%

Since both of these options only add new characters, I think this would be a completely backwards compatible change. Since no previous short URLs could have used those characters, they should never collide with previously generated short URLs.

As a final note, if USABLE_NAME_MAX_LENGTH = 12 can be reduced to match the prefix size (and assuming that size is 6) you get a much better chance of not hitting a disallowed character

    sum(8/64*(56/64)**i for i in range(6))  # ~55%

**Comment by RabsRincon** [comment]
Thanks for the great explanation, it was really helpful in this situation. I have followed your advice and reduced both the length and the amount of forbidden letters. I have also included a max try cap.

Again, thanks for taking the time to write such an extensive explanation :)
