### ISSUE TITLE
Overcaching of /api/compilers ?

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/compiler-explorer#1770]
When fixing #1768 I used this test locally to check the fix "worked". It's now deployed but this still shows some `null` and `"string"` output:

```
$ curl -q https://godbolt.org/api/compilers -H 'Accept: application/json' | jq -c '.[].alias' | sort | uniq -c
```

If you instead do:

```
$ curl -q https://gcc.godbolt.org/api/compilers -H 'Accept: application/json' | jq -c '.[].alias' | sort | uniq -c
```

(using gcc.godbolt.org) then you see the fixed version. I just tried the original query again after doing a CloudFront invalidation of `/api/*` and that "fixes" it but it implies we aren't giving the right cacheability headers for `/api/compilers`

**Comment by apmorton** [comment]
none of the responses from `/api/*` specify a cache-control header

For POST requests this is a non-issue because cloudfront will not cache POSTs.

For GET requests this means that cloudfront will cache the response for its default TTL of 86400 seconds (24 hours).

This duration can be changed in cloudfront: https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/Expiration.html

But we should probably add cache control headers to the api responses in any case.

**Comment by mattgodbolt** [comment]
Thanks Austin!
