### ISSUE TITLE
[BUG] clang 9+ fails to execute code

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/compiler-explorer#1780]
clang latest is failing to run with: https://gcc.godbolt.org/z/uYQrkM
./output.s: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by ./output.s)

**Comment by mattgodbolt** [comment]
Seems our usage of a more modern GCC libstdc needs a workaround: e.g. `-Wl,-rpath,/opt/compiler-explorer/gcc-snapshot/lib64/` on the command-line for now, or else some `LD_LIBRARY_PATH` manipulation on our side.

**Comment by mattgodbolt** [comment]
Interestingly gcc itself doesn't need this: https://gcc.godbolt.org/z/7XVr9P

**Comment by partouf** [comment]
Well, this is disappointing, I figured maybe this could be solved with a different --gcc-toolchain, but that's really just for compiling.

But I guess it makes sense that it looks for libstdc++.so.6 in /usr/lib instead of where the toolchain during compiling was.

This kind of also means this has been "wrong" always, but haven't noticed it until now.
Setting the -rpath makes sense. But it needs to be only during linking.

And it should probably depend on the compilers toolchain path.
There's code for libraries that autodetect and add paths, but this is a bit different.

Let's see if I can add support for this without making the code a total mess...

**Comment by partouf** [comment]
Fix is now live
