### ISSUE TITLE
[BUG] Global options configuration for compiler are not taken into account

### ISSUE THREAD

**Issue by jfalcou** [mattgodbolt/compiler-explorer#1899]
**Describe the bug**
Options set globally for c++ compilers are not taken into account.

**To Reproduce**
This is a sample config file that' doesn't work:
https://gist.github.com/jfalcou/17073aaaecf5ca1259a0ba628f6e2aae

**Expected behavior**
The -I options should be working and taken into account by every compilers

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Chrome

**Comment by RabsRincon** [comment]
Hi! Thanks for taking the time to open the issue.
Sadly the current options handling sees your options provided in line 15 as a default to use if no other options are set for a compiler.
On the other hand, this seems like a great feature to have so I went ahead and implemented it in d88bfcb. By supplying `baseOptions` instead of the `options` key you used, its contents will be prepended to every compiler option in its hierarchy.

Let us know if this helps :)

**Comment by jfalcou** [comment]
Just updated. It works perfectly !

**Comment by jfalcou** [comment]
Fixed in d88bfcb
