### ISSUE TITLE
Option to download the binary output

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/compiler-explorer#203]
Requested by Benjamin Motz over email

**Comment by AraHaan** [comment]
I totally agree also I would like to have an option to also download the resulting binary as well if possible. It would be a great way to actually look at and to get actually ``hex`` data from the actual offsets that it says in things like CFF Explorer on Windows (And yes I can open up ``ELF`` format assemblies in it).

**Comment by haneefmubarak** [comment]
Two issues come to mind with this:

 1. People may start (ab)using the service as a cross-compile-mill. That may result in extremely heavy load increases, which may make hosting the service unsustainable from the perspective of hosting costs.
 2.  Proprietary vendors may object to allowing their products to be used in `compiler-explorer` if their binary output can be downloaded, because [note: this isn't how I feel, but roughly the line of logic they tend to follow] people who only need a few functions thoroughly optimized may simply use the online service to optimize and download said functions and skip out on paying for [the vendors'] compiler[s].

**Comment by mattgodbolt** [comment]
Thanks @haneefmubarak for your input. Both are real issues. I need to come up with a decent solution for (ab)use, as I plan on launching a RESTful API for even the existing functionality, which will require some level of rate limiting/throttling. All that said though, currently I've been surprised by how well the existing infrastructure scales.

2. is mostly easily solved by not allowing this for Intel and other proprietary compilers.

**Comment by mattgodbolt** [comment]
I'm actually pretty convinced this is a bad idea now. As @haneefmubarak says we don't want to be a compilation farm, and implementing the infrastructure to support this is out of scope for now. If anyone feels strongly about this we can add it to the long term, but in the interests of keeping our issue list manageable, I'm closing this.

**Comment by mohitmv** [comment]
Hi @mattgodbolt  - I was checking latest thought process on this ?

If we have a global limits  MAX_BINARY_DOWNLOADS_PER_DAY_PER_USER ,  MAX_BINARY_DOWNLOADS_PER_DAY_OVERALL then it would be hard to abuse it and at the same time it will be easier for experimenter to experiment their stuff ?

What do you think ?

**Comment by AraHaan** [comment]
still a major risk why not just buy the tools you need and compile it on a box. Like for example if you want to test your program between windows, mac, and linux then use WSL on your linux box, and for mac use an actual Macbook that is cheap. Heck I was able to get a good macbook pro 13 in from 2015 for only 556$ and yet it has more ram that my windows pc (8 GB instead of 6), i5 instead of an i3, retina display instead of a touchscreen, and instead of an HDD which HDD’s nowdays are like the quality of using actual floppies, and overall much more responsive.

**Comment by mohitmv** [comment]
I just need Riscv-32-gcc compiler. It's freely available but setting it up is a process because it's prebuilt packages are not available. So I need to build from source along with its 40s dependencies. I just need it for experimenting something for couple of days.. I need to run some analysis on a generated ELF of riscv-32 architecture for couple of my C program (only 4 program, each of them has less than 50 lines).

**Comment by mattgodbolt** [comment]
> If we have a global limits MAX_BINARY_DOWNLOADS_PER_DAY_PER_USER , MAX_BINARY_DOWNLOADS_PER_DAY_OVERALL then it would be hard to abuse it and at the same time it will be easier for experimenter to experiment their stuff ?

How do we tell who a "user" is? We don't have any log in or tracking that can do this. So, right now, it's not an opion.

**Comment by mattgodbolt** [comment]
> I just need Riscv-32-gcc compiler. It's freely available but setting it up is a process because it's prebuilt packages are not available. So I need to build from source along with its 40s dependencies. I just need it for experimenting something for couple of days.. I need to run some analysis on a generated ELF of riscv-32 architecture for couple of my C program (only 4 program, each of them has less than 50 lines).

If you want the riscv-32-compiler that Compiler Explorer uses you can install the version we build with our installation tool `ce_install`, available from the https://github.com/compiler-explorer/infra repository.

```
$ ce_install install compilers/c++/cross/gcc/riscv32
Installing compilers/c++/cross/gcc/riscv32 10.2.0
2021-04-27 17:26:41,301 lib.installation INFO     Fetching https://s3.amazonaws.com/compiler-explorer/opt/riscv32-gcc-10.2.0.tar.xz (45195920 bytes)
2021-04-27 17:26:42,028 lib.installation INFO     100% of https://s3.amazonaws.com/compiler-explorer/opt/riscv32-gcc-10.2.0.tar.xz
2021-04-27 17:26:42,029 lib.installation INFO     Piping to tar Jxf -
2021-04-27 17:26:44,776 lib.installation INFO     Moving from staging (/opt/compiler-explorer/staging/gcc-10.2.0) to final destination (/opt/compiler-explorer/riscv32/gcc-10.2.0)
2021-04-27 17:26:44,780 lib.installation INFO     compilers/c++/cross/gcc/riscv32 10.2.0 installed OK
1 packages installed OK, 1 skipped, and 0 failed installation
$ /opt/compiler-explorer/riscv32/gcc-10.2.0/riscv32-unknown-elf/bin/riscv32-unknown-elf-g++ --version
riscv32-unknown-elf-g++ (crosstool-NG UNKNOWN) 10.2.0
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

The tarball is available too directly from https://s3.amazonaws.com/compiler-explorer/opt/riscv32-gcc-10.2.0.tar.xz

**Comment by breck7** [comment]
Suggestion: what about adding a Download binary button, and then when someone clicks it, pop a message that says something along the lines of "This is not supported yet, for reasons ... ".

The reason is just that it seems like an obvious feature, and I was looking around for a while for it, thinking I just must not have seen it somewhere.

Just a nit/suggestion! Not important.

**Comment by qwazwsx** [comment]
RE: preventing a compilation farm

What about proof of work? Have the server send over a computationally expensive problem that the client has to solve in order to download the file. Maybe scale the difficulty based on the length of the program being compiled to make sure it's not economically feasible to turn your servers into a farm.

**Comment by sei-eschwartz** [comment]
I would think that the ability to execute code and show its output is a larger target for abuse than becoming a compile farm.

This would be a very useful feature for me.

**Comment by JamesNewton** [comment]
Users (read: "Students") on devices which do not allow the installation of compilers (read: Chromebooks / Libraries / School computers) would find it very useful to download binaries or for cross loading into small computing platforms.
