### ISSUE TITLE
Closing a compiler window should close all its outputs

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/compiler-explorer#482]
Not trivially reproducible; but @elkvis on slack mentioned he had a link and ended up having an output thing.

**Comment by elkvis** [comment]
The link that eventually led to discovering the bug was https://godbolt.org/g/RebNta

**Comment by RabsRincon** [comment]
On #492 the same thing happens. A compiler output is open but not its compiler. A reproducible link is found [here](https://gcc.godbolt.org/#g:!((g:!((g:!((g:!((h:codeEditor,i:(j:1,source:'%23define+SIZE+1024*1024%0Aunsigned+long+sum8(unsigned+char+*__restrict__+a)+%7B%0A++++unsigned+long+sum+%3D+0%3B%0A++++for+(int+i%3D0+%3B+i%3CSIZE+%3B+i%2B%2B)+%7B%0A++++++++sum+%2B%3D+a%5Bi%5D%3B++//+compilers+suck,+and+don!'t+know+how+to+use+vpsadbw+for+this%0A++++%7D%0A++++return+sum%3B%0A%7D%0A%0A%23include+%3Cvector%3E%0A%23include+%3Ccstdint%3E%0A%23include+%3Cnumeric%3E++//+accumulate%0A%23include+%3Calgorithm%3E%0A%23include+%3Cbitset%3E%0A%0A//+very+good+with+clang+-stdlib%3Dlibc%2B%2B%0A//+otherwise+total+garbage+with+clang+and+gcc%0Auint64_t+popcnt_boolvec(const+std::vector%3Cbool%3E+%26v)+%7B%0A++++//uint64_t+sum+%3D+std::accumulate(v.begin(),+v.end(),+0ULL)%3B++//+terrible%0A++++uint64_t+sum+%3D+std::count(v.begin(),+v.end(),+true)%3B++//+terrible%0A++++return+sum%3B%0A%7D%0A%0Auint64_t+count_bitset(const+std::bitset%3CSIZE%3E+%26v)+%7B%0A++++return+v.count()%3B%0A%7D%0A%0A%23include+%3Cboost/dynamic_bitset.hpp%3E%0A//+scalar+byte+LUT%0Auint64_t+sumdynamic_bitset(const+boost::dynamic_bitset%3C%3E+%26v)+%7B%0A++++uint64_t+sum+%3D+0%3B%0A++++return+v.count()%3B%0A%7D%0A%0A//+good%0Avoid+db_and(boost::dynamic_bitset%3C%3E+%26a,+const+boost::dynamic_bitset%3C%3E+%26b)+%7B%0A++++a+%26%3D+b%3B%0A%7D%0A%0Along+db_ff(const+boost::dynamic_bitset%3C%3E+%26b)+%7B%0A++++//+pretty+good:+checks+64+bits+at+a+time,+but+doesn!'t+vectorize%0A++++return+b.find_first()%3B%0A%7D'),l:'5',n:'0',o:'C%2B%2B+source+%231',t:'0')),header:(),k:35.52330203177444,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:compiler,i:(compiler:clang400,filters:(b:'0',commentOnly:'0',directives:'0',intel:'0'),options:'-stdlib%3Dlibc%2B%2B+-std%3Dgnu%2B%2B11+-Wall+-O3+-march%3Dnative+-I/opt/compiler-explorer/libs/boost_1_64_0+-fno-unroll-loops',source:1),l:'5',n:'0',o:'x86-64+clang+4.0.0+(Editor+%231,+Compiler+%233)',t:'0')),k:30.217942285737152,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:compiler,i:(compiler:g71,filters:(___0:(),b:'0',commentOnly:'0',directives:'0',intel:'0',jquery:'3.2.1',length:1,prevObject:(___0:(sizzle1501393868964:(undefined:(legend:!(34038,0,'1')))),length:1,prevObject:(___0:(jQuery321025565795414854021:(display:''),sizzle1501393868964:(undefined:(legend:!(34038,0,'1')))),length:1))),options:'-std%3Dgnu%2B%2B11+-Wall+-O3+-march%3Dnative+-fverbose-asm+-I/opt/compiler-explorer/libs/boost_1_64_0',source:1),l:'5',n:'0',o:'x86-64+gcc+7.1+(Editor+%231,+Compiler+%231)',t:'0')),k:34.258755682488406,l:'4',n:'0',o:'',s:0,t:'0')),l:'2',m:76.79112008072654,n:'0',o:'',t:'0'),(g:!((h:output,i:(compiler:3,editor:1),l:'5',n:'0',o:'%233+with+x86-64+clang+4.0.0',t:'0')),header:(),l:'4',m:23.20887991927346,n:'0',o:'',s:0,t:'0')),l:'3',n:'0',o:'',t:'0')),version:4)

Note how the output is from compilerId 3 but only compiler 1 & 2 exist
