### ISSUE TITLE
Binary view broken

### ISSUE THREAD

**Issue by sergof** [mattgodbolt/compiler-explorer#484]
Characters are mangled, also long lines are cut off:
![bug](https://user-images.githubusercontent.com/484829/28241885-20cc1a62-699e-11e7-8d9f-cd001cd6926b.png)

Tested in Firefox and Chrome on Linux and Windows.

**Comment by RabsRincon** [comment]
Good spot!
But, it is a known issue I've been trying to fix for somw days now. 
Once I get home I should be able to fix it for good. Give me 2-3 days! :)

**Comment by sergof** [comment]
Glad to hear that :)
I forgot to mention that tooltips don't work either.
The lines being cut off was an issue for quite a while and the tooltip was the only way to see the whole line.
Would be good if it wouldn't be needed anymore.

**Comment by RabsRincon** [comment]
So! Good and bad news. Turns out Monaco clamps the size of the line numbers to a value too small. I've asked them for a way to change this (https://github.com/Microsoft/monaco-editor/issues/515) but that will take a while.
 I've a nasty work around by reducing widths and font sizes, but that's not ideal as it will get too unreadable in many situations. 
But that's better that what's currently in, as this workaround will at least get the tooltips working again

Hopefuly in a few months (Monaco development cicle somewhere around 3 months) we can expand the width of the line numbers and a better solution can be implemented

Don't hesitate to open another issue if you find any other problems :smile:

**Comment by mattgodbolt** [comment]
Rubén's fix is deployed; seems to have improved things a fair bit. Let's hope the Monaco folks are receptive. Ironically when I asked them about having per-line annotations for the binary view in the first place, they suggested using line numbers :)

**Comment by sergof** [comment]
Cool, thanks for the quick response.
It's of course not ideal but workable :)

**Comment by RabsRincon** [comment]
So! I dug a bit into the Monaco editor API and found a way to force a larger lineNumber width. Note that this relies on internal API and might stop working at some point, but this seems to be the only solution available. 
I'm so sorry this took so long to get sorted :)
