### ISSUE TITLE
More up to date Go?

### ISSUE THREAD

**Issue by AlexMax** [mattgodbolt/compiler-explorer#536]
The canonical version of Go (as in, not gccgo) on godbolt is a little out of date.  Go is currently on version 1.9, and has undergone significant changes since 1.4 - in particular, a new SSA back-end has been added as of 1.7, so the differences should be significant.

**Comment by RabsRincon** [comment]
Ey! Thanks for this! Go really did need some attention at CE.
I've been looking into it and there's a good reason for 1.4 to be the latest version here. Since 1.5, Go moved to a unified tool instead of the old g4 g6 etc, which makes it harder for us to implement it

But! That's not saying it's not possible to implement. We'll just need more time! For the time being tho, I'll add the latest gccgo version (The one that comes with GCC 7.2.0, which if https://golang.org/doc/install/gccgo#Releases is accurate, should have a Go 1.8 implementation) in the hopes that that's ok/enough while we can figure out a way to implement the newer versions

I can't however give you an ETA, sorry!

**Comment by AlexMax** [comment]
Hi there.

Thank you for your response.  Sorry for the long delay in responding, but
it is possible to make modern Go dump assembly.

https://golang.org/cmd/compile/

Are there other things necessary for your tool?  I ask this from a place of
ignorance.  If there are missing pieces, I'm sure the Go developers might
consider your requests, as your tool is incredibly awesome.

The problem with GCCGo is that in my experience it doesn't seem to get a
lot of use in the greater Go community, and the output of the two compilers
aren't comparable.

-Alex

**Comment by mattgodbolt** [comment]
That looks about right. CE expects to be able to run a single command and have it "just work" to generate ASM. As long as we can run `go tool compile ...` with a different `go` command for each version of Go, we're in business. Last time I looked I had to define a bunch of environment variables per `Go` version to point at different roots, and that made it less trivial to add. Is that still the case?

**Comment by AlexMax** [comment]
At least in my quick testing (Go 1.7.3 installed from the website on Linux), you do not need environment variables for getting a source listing for an arbitrary random `.go` file.

    go tool compile -S -S test.go
    "".main t=1 size=179 args=0x0 locals=0x58
            0x0000 00000 (test.go:5)        TEXT    "".main(SB), $88-0
            0x0000 00000 (test.go:5)        MOVQ    (TLS), CX
    ... elided ...

Go's assembler output is kind of odd, and is not a 1:1 representation of the underlying instructions for a particular architecture, but it is what Go developers expect to see.  The assembler is documented in more detail [here](https://golang.org/doc/asm), if you're curious about its idiosyncrasies or need some guidance.

Since Go 1.5, there are environment variables that you can set to output assembly for different platforms and environments.  `go tool dist list` lists them all, and you can set `GOARCH` and `GOOS`.  However, I've only messed around with this a little bit, and I think one must ensure that the standard library exists for that architecture/environment combination before using the compile tool.  I will update this issue if I have more insight later.

**Comment by AlexMax** [comment]
As far as multiple Go versions are concerned, I found [this post](https://medium.com/@vCabbage/go-installing-multiple-go-versions-from-source-db5573067c) that recommended compiling Go from source.  The directions don't look too terribly difficult to follow, and when you're done, you don't even need to change `GOROOT` or anything similar.

**Comment by RabsRincon** [comment]
Uhg. Sorry for taking so damn long
 
Here are a few interesting points:
Turns out GoLang includes `pkg/tool/linux_amd64/compile` which lets you directly compile code (As far as I can tell!) so there's no reason to call go with different env variables.
Between 1.4.1 and 1.8.x, the assembly output changed a bit so we needed a new filter to remove boring parts of the outputted asm

Now, the new compilers are: 1.7.2, 1.8.5, 1.9.2, and in the future, it will be much easier to add newer ones.

I've called them "x86-64 GoLang 1.X.X" for the lack of a better name. I can however change this, so if you think a better naming for them could work, please don't hesitate in suggesting them!

I want to thank you for pushing us towards better Go support on CE, and for being able to wait almost 2 months without a response

:)

PD: I'm closing the issue but feel free to answer here if you have any more questions!

**Comment by mattgodbolt** [comment]
Pushing to beta right now so you can take a look

**Comment by mattgodbolt** [comment]
( https://go.godbolt.org/beta ... https://godbolt.org/g/hWmKzB for example)

**Comment by AlexMax** [comment]
Wow, this looks pretty spiffy.  Thanks for taking the time to implement this.

Unfortunately, it appears that I can't import the stdlib for some reason.

```
package main

import (
	"fmt"
)

func main() {
	fmt.Println("Hello, playground")
}
```

Trying to run this on godbolt results in "can't find import fmt" errors.

**Comment by AlexMax** [comment]
As for naming, it appears that the golang website uses the term `gc` to refer to the canonical compiler in several locations, as opposed to `gccgo`.  It calls the architecture (`GOARCH`) `386` or `amd64` depending on if it's x86 or x86-64.  It also calls the operating system (`GOOS`) `linux`.

I would change the compiler name at the very least.  Architecture - it's up to you.

**Comment by mattgodbolt** [comment]
@AlexMax thanks for checking it out. Re standard libraries, seems like it's the problem `6g` has had: #69 . I'm not knowledgeable enough in how `go` works to start fixing this, any advice appreciated.

With respect to naming, we'd be happy to rename to `gc` to make it more consistent with the naming convention. Thanks for your input!

**Comment by RabsRincon** [comment]
So, we are going places!
![image](https://user-images.githubusercontent.com/5364255/33182613-068fd8bc-d075-11e7-8bc3-8015e36a504c.png)
Needs some bugfixing before I can push it, but we're closer than ever!

**Comment by RabsRincon** [comment]
Ok, so I've hit a roadblock with 1.8.and 1.7. With the newer 1.9, go is able to guess the GOROOT variable automatically (https://golang.org/doc/go1.9#goroot) which makes it possible for us to use it at all.
Older versions need either a GOROOT env variable (Which is out of the question for us) OR to be built from source, where you can set a custom GOROOT_FINAL variable that wil be backed into the binaries (As the article you linked mentions)
So I guess next step here is to build 1.7 and 1.8 from source, but as we do support the newer version, I think we can safely mark this issue as completed, and create a new one to track there the building from source.

We do have one problem tho. 1.4 can either:
1) Stay like it's been until now: Libraries won't work (We can't set env variables with mroe than 1 version of go installed!)
2) Remove it and have old links use the 1.9.2 version
3) Remove it, break old links -> Not gonna happen. **Url should live forever!**

If anyone has any idea, please let me know

**Comment by mattgodbolt** [comment]
We can try and supply a `GOROOT` when we execute the compiler. The environment is already modified to include some GCC stuff like `LIBRARY_PATH` for multiarch support...so it's possible!
