### ISSUE TITLE
GFortran?

### ISSUE THREAD

**Issue by zbeekman** [mattgodbolt/compiler-explorer#549]
How involved is it to add a new compiler? It would be great to have GFortran added, many/most flags are shared with gcc.

**Comment by mattgodbolt** [comment]
Pretty easy. The main problem is building all the compilers, which currently I do manually using scripts in the sister project mattgodbolt/compiler-explorer-image. They currently don't build fortran, but I can add it, then update the nodes etc.

Syntax colouring would need to be added too. That's fairly easy to do, but takes time.

This might all work better after #277 is implemented.

**Comment by zbeekman** [comment]
I'd love to see this implemented. I would probably be of more use updating mattgodbolt/compiler-explorer-image than I would implementing syntax highlighting...

**Comment by mattgodbolt** [comment]
Amazingly I'm already building the fortran compilers (I forgot I enabled them already...)

```
ubuntu@ip-172-30-1-211:~$ /opt/compiler-explorer/gcc-7.2.0/bin/gfortran --version
GNU Fortran (GCC-Explorer-Build) 7.2.0
```

so, this is a step closer than I thought!

**Comment by zbeekman** [comment]
Great! Then there's probably not much for me to help with. Thanks!

**Comment by LadaF** [comment]
@zbeekman  Indeed, one can currently invoke the gfortran frontend by `-x f95` for those GCC versions for which gfortran is built. It is a nice feature.

**Comment by mattgodbolt** [comment]
I'd forgotten about -x in this way :). It will still be great to build
Fortran into more of the compilers and to have it officially supported with
syntax highlighting etc too, so will leave this bug open.

**Comment by dbroemmel** [comment]
Since I was also interested in Fortran support for this amazing tool, I've started experimenting with it.
[https://github.com/FZJ-JSC/compiler-explorer](https://github.com/FZJ-JSC/compiler-explorer)
I believe it's very basic for now, but it seems to work at least to some level. The build process for compilers is not touched, it rather relies on compilers it finds installed on the machine.

Initial bits on syntax highlighting are added as well, but I don't yet understand how it's supposed to work. I am aware of missing parts here and would also love to see indenting, but it's a start.

Not sure when I'll find the time to extend it further. If it reaches a more finished state I'll make a pull request (unless you feel a PR is worthwhile already).
