### ISSUE TITLE
Reverse proxy

### ISSUE THREAD

**Issue by yhtang** [mattgodbolt/compiler-explorer#634]
I really love this project and was trying to deploy it on my personal webserver. I would like to put it in a docker container behind some Apache reverse proxy, like:

```
<VirtualHost *:443>

ServerName              my-host

SSLCertificateFile      /etc/pki/tls/certs/my-host.crt
SSLCertificateKeyFile   /etc/pki/tls/private/my-host.key
SSLCertificateChainFile /etc/pki/tls/certs/my-host.ca-bundle

ProxyPreserveHost on

  <Location /cex>
    ProxyPass        http://172.17.0.4:10240
    ProxyPassReverse http://172.17.0.4:10240
  </Location>

</VirtualHost>
```

However, the page frequently fails to load (no CSS), and even if it loads the compilation still fails. This does not happen if I directly access via the docker container's ip.

Could you please show me how to correctly configure reverse proxy for CE?

**Comment by mattgodbolt** [comment]
Hi. The main Compiler Explorer site runs in docker using reverse proxies. The configuration for that is here:  https://github.com/mattgodbolt/compiler-explorer-image/blob/master/nginx/default

I don't use SSL on the main site as Amazon's load balancer takes care of that. I don't have much more wisdom to offer on this I'm afraid - hope the link above helps.

**Comment by yhtang** [comment]
I realize the problem was probably due to the fact that I am redirecting a relative url (/cex) from the reverse proxy host to a different one in the container (/).

Is there a way specify the relative url on which the compiler explorer server will be served?

**Comment by mattgodbolt** [comment]
There isn't a way to do that, but I don't think I understand why you need it. I'm using nginx to redirect /beta to / and I rewrite the URLs there. That said we can add a command line parameter to change the root

**Comment by mattgodbolt** [comment]
There isn't a way to do that, but I don't think I understand why you need
it. I'm using nginx to redirect /beta to / and I rewrite the URLs there.
That said we can add a command line parameter to change the root

**Comment by dsvf** [comment]
I was able to achieve this with the following Apache configuration:

```
<VirtualHost *:443>
    [...]
    RewriteEngine on
    RewriteRule ^/vs/(.*) http://localhost:10240/vs/$1 [P]
    RewriteRule ^/dist/(.*) http://localhost:10240/dist/$1 [P]
    RewriteRule ^/api/(.*) http://localhost:10240/api/$1 [P]
    RewriteRule ^/source/(.*) http://localhost:10240/source/$1 [P]
#    RewriteRule ^/min-maps/(.*) http://localhost:10240/min-maps/$1 [P]
</VirtualHost>

<Location "/ce">
#        AuthType Basic
#        AuthName "CE"
#        AuthUserFile /etc/httpd/.htpasswd
#        Require valid-user
        ProxyPass http://localhost:10240
        ProxyPassReverse http://localhost:10240
</Location>
```
Comments:

- The [P] (proxy flag) at the end of the rewrites is important for /api (to rewrite POST request correctly), and to proxy-redirect the request to localhost:10240. Otherwise you would have to rewrite it to https://example.com/ce/vs/$1 etc. 

- The min-maps rewrite might be necessary, although it works for me without it.

- Note: this forwards _all_ requests to https://example.com/vs (etc...) to CE, so if you have some other site living on example.com/vs it will not be available anymore due to the rewrites.

- The first four lines in the Location directive are optional (for password authentication) and are not necessary for reverse proxying.

- The only thing missing is the favicon.ico, but since rewriting the path to the favicon would set the favicon for all Apache-served sites to the green CE gears logo, I didn't bother.

**Comment by apmorton** [comment]
FWIW, you could probably simplify this significantly now. I'm not sure when it was added, but CE now has a configurable httpRoot option, which you can see here: https://github.com/mattgodbolt/compiler-explorer/blob/master/etc/config/compiler-explorer.beta.properties#L2

You can make a file in that folder called `compiler-explorer.local.properties` and add a `httpRoot=/ce` line.

Your rewrites shouldn't be necessary after that, just a simple proxy pass like you have at the end.

**Comment by dsvf** [comment]
I added a file `CE/etc/config/compiler-explorer.local.properties`, but the requests are still going to https://example.com/vs/... and not https://example.com/ce/vs/... so I don't know if some additional config is necessary for this.
My CE is the git clone from "a few days ago", but I'll try it with the very latest.

**Comment by apmorton** [comment]
Can confirm `httpRoot` is partially broken when `NODE_ENV=DEV`.
How are you running the node process?

If you run with `make run` it should work.
If you run with `make dev` `httpRoot` will be broken.

**Comment by dsvf** [comment]
It works with `make run` (and with `make`) but it requires me to add the subdirectory to the ProxyPass configuration:

```
<Location "/ce">
        ProxyPass http://localhost:10240/ce
        ProxyPassReverse http://localhost:10240/ce
        AddOutputFilterByType DEFLATE text/html text/xml text/css application/xml application/javascriptapplication/javascript
</Location>
```
There are no more CE-related entries in the VirtualHost directive, and no rewriting is needed.

In addition, I enabled on-the-fly compression to Apache. This reduces the initial page load size of ~3.9MB to 1MB, which helps me when using a slow connection (-> the AddOutputFilterByType).

Concerning the `make` vs. `make run` - I see `default: run` in the makefile, so I think adding `run` should not have made a difference. I guess that means that what I wrote [a few days ago](https://github.com/mattgodbolt/compiler-explorer/issues/634#issuecomment-511038419) was not using my updated configuration.

**Comment by mattgodbolt** [comment]
Gonna close this due to inactivity, and I _think_ things worked out, right?

**Comment by bjodah** [comment]
For posterity (googling reverse proxy and compiler-explorer lead me to this issue):

With the help of @apmorton (and @partouf) I managed to host a compiler-explorer instance in docker with port 10240 (`--publish 10240:10240`), and serving it over https under a URL prefix, by using a reverse proxy in my nginx server on the same host machine (so that I can share a link like https://example.com/compiler-explorer).

Here's the relevant nginx config section:
```
location /compiler-explorer {
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_buffer_size          128k;
        proxy_buffers              4 256k;
        proxy_busy_buffers_size    256k;

        proxy_pass http://127.0.0.1:10240;
}
```

note that inside the docker container, make sure to edit httpRoot to be /compiler-explorer

This can be achieved e.g. this way:
```
$ echo "httpRoot=/compiler-explorer">>etc/config/compiler-explorer.defaults.properties
$ make run
```

```
