### ISSUE TITLE
Customized hosting shorturl support regression

### ISSUE THREAD

**Issue by lichray** [mattgodbolt/compiler-explorer#768]
`GOOGLE_API_KEY` is dropped since cf407a85, now specifically accesses AWS configurations, while at least should access `etc/config/compiler-explorer.local.properties`.

**Comment by RabsRincon** [comment]
Hello! You're right we dropped the ball on that one. We try hard to support custom usages of CE, so we should have seen this one coming, so sorry for this! I like your suggestion, so I'll push something in a bit.

Thanks for helping us improving CE :)

**Comment by mattgodbolt** [comment]
If the api key is not found from amazon directly it checks aws.*.properties. When I run locally I set `aws.local.properties` to have `googleApiKey=xxxx`

Hopefully that closes this?

**Comment by lichray** [comment]
Yes, that works, although the key still has to appear in two places.

**Comment by mattgodbolt** [comment]
Which other place does the key have to appear? There are two distinct
Google API keys: one is used in the JavaScript client to create short URLs,
the other is used by the server to unpack them. I use different keys as I
severely restricted the client side one to prevent misuse.

Worth noting that we are planning on moving to a home grown solution for
links at some point soon. We will do our best to maintain the Google link
creation too so that users like yourself can continue to use it too.

Thanks! Matt
