### ISSUE TITLE
Show latency for assembler instructions

### ISSUE THREAD

**Issue by Hiradur** [mattgodbolt/compiler-explorer#80]
To get a better understanding of how long some assembler instruction take in relation to others it would be great to be able to choose a CPU architecture and see the corresponding latencies for the assembler instructions.

Agner Fog has a comprehensive collection of latency measurements available on his site:
http://www.agner.org/optimize/#manuals (see 4. Instruction tables, also available in *.ods format)

**Comment by mattgodbolt** [comment]
Great idea. Very tricky to get right though; and obviously very
architecture dependant. Latencies are only a part of the picture: to be
more useful the whole pipeline needs to be taken into effect, with all the
execution ports and inter-instruction dependencies modelled.

I've started looking into this latter part before and it's extremely
non-trivial. For what it's worth I did a presentation on some of the
complexities: http://youtu.be/hgcNM-6wr34 :)

**Comment by Hiradur** [comment]
I agree it would be tricky to make it reflect actual execution performance.
However, I think it would already help to see the latency for individual instructions out of their execution context. A textbox should warn that performance of the whole set of instructions will differ.
It would be enough to get a basic picture of which instructions are fast and which are slow and should be avoided if possible.

Great talk btw, I learned some new stuff.

**Comment by AndreiBarsan** [comment]
I would very much like to see this as well. I don't think I've ever seen something like this before.

Moreover some newcomers end up thinking that the processor is able to execute exactly one instruction per clock cycle, which is wrong, at least on most major architectures. A feature such as this one could help avoid this early confusion.

**Comment by mattgodbolt** [comment]
I agree; but to accurately show what the CPU is really doing is very tricky. In some cases the instructions are effectively taking a third of a cycle each (measured by issue rate), and with the out of order core able to have ~100 instructions in flight at once it's never that obvious how "long" one instruction is.

That said it would be a great step to be able to annotate the instructions with all the information and at least present it for further interpretation.

I will think more on this: hidden away also is all the padding and NOPs the assembler generates. GCC explorer stops before assembly and works on the text output. I've long thought it should really operate on the binary output, which captures much more of this information but is considerably harder to do in a cross-platform way.

Thanks for your input!

**Comment by pcordes** [comment]
You could maybe incorporate IACA (https://software.intel.com/en-us/articles/intel-architecture-code-analyzer), so people could #include <iacaMarks.h> and put IACA_START as the first instruction in a loop, and IACA_END as the last instruction in a loop.

IACA is currently unmaintained closed-source freeware from Intel, and only has modes for Nehalem to Haswell, and it's nowhere near perfect (e.g. wrong data for some instructions), but it's not bad for a rough guess.

**Comment by mattgodbolt** [comment]
@pcordes I've considered this before, but it seems like although it's freeware (as in you don't pay for it)...its license is unclear. https://software.intel.com/protected-download/267266/157552 has details and I've been put off before by "...internal testing and development of your products" restriction.

It would be a nice addition though, so I'll seek advice. Intel themselves have stopped responding to my emails (hence ICC is stuck in the stone ages)..

**Comment by haneefmubarak** [comment]
Potential solution: add a field for microarchitecture (to be passed as `-march=`). Then that microarch that be used to lookup instruction timings from a JSON that contained all the instruction timings.

I use gcc-explorer and Agner's timings a LOT, so if we do something like this, I would love to create a script (client side JS) that does the related lookups and returns a list of latencies (latency per line).

**Comment by elalfer** [comment]
I'd love to see this functionality as well. @mattgodbolt Is it only licensing issue to integrate IACA?

**Comment by pcordes** [comment]
@haneefmubarak: Dependency analysis is the other key part of the puzzle.  The same instructions with independent operands  (ILP) can be a lot faster than if they form one long dependency chain.  And some loops have loop-carried dependencies while others don't.

So I don't think it's *that* useful to just annotate with latency.  Throughput / number of uops maybe, but latency without dependency analysis is only barely useful.

**Comment by haneefmubarak** [comment]
@pcordes ahaha of course. Even better than that is that execution analysis varies by processor because what you're essentially doing is simulating the execution of a stream of instructions (in fact, I usually do it by hand and it takes hours on end for less than a hundred cycles).

That being said, just dumping timings can be useful - I suppose perhaps we could make it such that different timings can be selected for displaying:

 - Latency
 - Reciprocal Throughput
 - Ports/Lanes/Execution Units
 - uops

Does that sound fair?

**Comment by pcordes** [comment]
@haneefmubarak: yeah, looking up all 4 of those Agner Fog's tables would be significantly better than just latency.  It's nowhere near as useful as IACA output, but it's certainly better than nothing.  

[The fused-domain uop count depends on the addressing mode, for memory operands](http://stackoverflow.com/a/31027695/224132).  Even before SnB, there are some limits on what can micro-fuse.  But SnB can't micro-fuse any indexed addressing mode (at least, not in the out-of-order core.  It "un-laminates" them at issue.  Apparently Skylake doesn't un-laminate indexed addressing modes.  So putting the logic to work this out into the Compiler Explorer would certainly be useful.  It still only requires looking at each instruction in isolation, with no context.  (Unlike for macro-fusion, which can be disrupted across a 64B alignment boundary on SnB-family.)

Also note that recip throughput is often not relevant, since different instructions compete with each other for the same ports.  It only adds new information (beyond ports and uop count) for instructions like `divps` that aren't fully pipelined.

Also potentially interesting, and useful for software to count for you: how uops slot into Ways in the uop cache.  (Up to 3 ways can cache uops from a 32B block of x86 code).  The trouble with that is that you'd have to decide which branch targets were important to start counting from.

It would be useful to give humans a start looking from frontend effects from busting the uop cache.  Micro-coded instructions like [integer `DIV` can surprisingly easily bottleneck on the frontend](http://stackoverflow.com/q/26907523/224132), so alignment can matter.  Surprisingly, not fitting in the uop-cache can actually be better for DIV (see BeeOnRope's answer for Skylake on that linked SO question), so it's not even just a case of "good" vs. "bad".

**Comment by mattgodbolt** [comment]
I love this thread: @pcordes thanks for your amazing comments here.

There are *so* many ways to go here. IACA is one. I personally don't find its output useful, but I appreciate everyone gets something different from it.

My other projects include javascript CPU emulators, and I've long toyed with the idea of doing a cycle-level emulation of the x86 using Agner's tables....but whenever I've started I've had to give up: there's still so much black magic and unknowns. Plus; it's very hard to scale across each processor - there's a tonne of variables across each.

So; I'm happy to have this bug open as a source of inspiration, and I welcome anyone's further thoughts (and/or sketches in branches etc), but I can't see much moving on this at the moment.

**Comment by pcordes** [comment]
> cycle-level emulation of the x86 using Agner's tables

Yeah, I've had the same idea, then realized just how daunting a task that would be.  Even without modelling the cache/memory subsystem or branch prediction, there are still so many unknowns.  The algorithm the scheduler uses to pick uops out of the RS is a black box, but it's what determines whether uops on the critical path are delayed by resource conflicts or not.  (i.e. it's what stops Haswell for sustaining its peak 64B load / 32B store per clock, because even single-register store uops sometimes steal p23 instead of using the store-only simple-AGU on p7.  Intel's optimization guide has even published a table (in their optimization manual) with the best-case sustained L1 cache throughput as ~81B per clock, rather than 96).

I think this kind of effect is what's happening in [this Significant FMA performance anomaly experienced in Intel Broadwell](http://stackoverflow.com/questions/34309707/significant-fma-performance-anomaly-experienced-in-the-intel-broadwell-processor) (vs. HSW and SKL) SO question, where significant effort and much perf-counting only resulted in wild guesses.  e.g. perhaps Broadwell's lower latency for some FP ops led to different scheduler decisions.

BTW, I don't use IACA very often, since it's clunky and not the easiest thing to use.  It's maybe most useful for getting a handle on the critical path of code I didn't write.  It's actual throughput numbers are often highly suspect, but the marking up of the disassembly is useful (modulo bugs like thinking SHRD is slow on SnB, IIRC).

**Comment by elalfer** [comment]
It is almost impossible to write a reasonable CPU simulator based on the public information, even if one would simplify memory model. And any implementation would be too far away from the actual model, so it might only add a lot frustration. There are really small number developers that care about performance so much they want to know everything about the microarchitecture.

I think, pointing out following information might be already very beneficial for a lot of developers:
- performance critical dependency chain/path 
- latency and throughput for loops and each instruction
- port load balance - for example ,if the code is port 5 limited or not, which is quite a big problem on HSW+ with AVX2 for video processing algorithms (shuffles/permutes/broadcasts etc.)

Maybe very simplified simulator with perfect scheduling would work no worse than any other implementation and provide about the same level of details. Basically, if you can get better implementation on such simplified simulator and/or IACA one might expect better results on HW in the most of the cases. I see no need to overcomplicate it.

**Comment by pcordes** [comment]
@elalfer: yeah, that would be nice.  I agree that something simple can still be very useful.  I'd add to your list: total fused-domain uop count.  That's easy to count, and often relevant:  The front-end can easily be the bottleneck in code with a good mix of uops (assuming perfect memory performance).

Finding the dependency chains between instructions is non-trivial, though.  IDK how practical that is in Javascript, or in server-side stuff.  You'd at least need a table of which x86 instructions depend on their output and which don't.  (And which instructions modify multiple operands, like XADD).  Probably we don't want to have the compiler dump its internal GIMPLE or LLVM-IR data-flow representation, since then we'd need compiler-specific code.

Highlighting separate dependency chains with different colours would be really cool, if it's feasible.  The first version of this will probably just give up on loops with complex branching inside the loop.  It would be useful even if it only worked like IACA, and assumed all branches inside the loop were not-taken, except the bottom one.  But IACA requires you to mark the start/end manually, instead of detecting loops on its own.  I'm worried that might be a hard problem.  Still, detecting backwards conditional branches and assuming they're loops might not be a bad start.

I just used IACA for something yesterday, and I'd forgotten how un-helpful the output was.  It doesn't really identify the separate dependency chains for you; it just marks one set of instructions as being on "the critical path". :/  That can be due to resource conflicts with the critical path dep chain or whatever.  IACA seems mostly just useful for uop port balance (which is slow to do by hand).
