### ISSUE TITLE
Changing the source name makes diagnostic messages look ugly and breaks error highlighting

### ISSUE THREAD

**Issue by Rakete1111** [mattgodbolt/compiler-explorer#867]
If I change the name of the current source programmatically, the error message is not nice (as in, the coloring is different, more black and red type instead of blue colored) and the inline error highlighting breaks down, as in doesn't work anymore.

You can see it in action here: https://godbolt.org/g/QrBtNu

**Comment by mattgodbolt** [comment]
I don't know of a way to fix this. Short of parsing the preprocessor directives myself (plus the equivalent for the other languages we support), there's no obvious way to tell you've lied to the compiler about the name of the file.

Compiler Explorer uses the name it picks for the compilation file to be able to discriminate between the code supplied by the user and code coming from `#include`d files.

The lack of blue is because it's no longer a hyper-link to select the source it came from. Likewise the lack of highlighting in the source editor is because it doesn't know how to map the error messages back to the source.

I appreciate any ideas on how to fix this.

**Comment by mattgodbolt** [comment]
I'll happily re-review any new PRs you might come up with, but for now I'm closing as I can't see a way to fix this rare case. Thanks for trying!
