### ISSUE TITLE
auto-fold has stopped working

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/compiler-explorer#869]
Editors starting with `// setup` or similar should auto-fold...

https://godbolt.org/g/bnkzbr

but that seems to have stopped working!

**Comment by RabsRincon** [comment]
The only way I've been capable of making this work is by wrapping the `run` call in a timeout of some ms, at which point the editor does fold the code.
The problem is, this would not fix the underlying issue (if you can call it issue). The editor won't listen to calls like the event folding run until the page has been fully initialized.

**Comment by mattgodbolt** [comment]
Workaround is horrible, but "good enough" for now.
