### ISSUE TITLE
Unusual line attribution

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/compiler-explorer#958]
See https://godbolt.org/g/vcfRgC and note that the first `rms` is line-attributed, but the `rms2` is not. Then switch the order of definition and note the reverse is true. Didn't have time to check whether this is a GCC thing, but 8.1 and 7.3 suffer from it, though clang does not.

**Comment by partouf** [comment]
The .loc labels seem to be missing from the function, but even worse...
the asm it produces looks... incorrect?

![image](https://user-images.githubusercontent.com/442630/48105727-e69e9a80-e238-11e8-8853-db141f8df4e3.png)

the call to rms2() in main() calls rms() instead... (same in binary mode)

could this be because rms and rms2 actually do the same thing, and it thinks it only needs one version of the same code?

**Comment by partouf** [comment]
Interesting. That one is just not attributed in binary mode, so I assume it will still optimize it away. In the normal mode it works.

if i wrap extern "C" {} it explicitly names the functions, but rms2 is duplicated to inline into main, and thats the version that is line attributed.

**Comment by mattgodbolt** [comment]
Closing this: I am not sure it's CE's fault (although I'm tired and maybe just overzealous to close things)
