### ISSUE TITLE
MSVC Pre 2018 is not the best name

### ISSUE THREAD

**Issue by danilaml** [mattgodbolt/compiler-explorer#959]
I think it;s a bit confusing. It's great to have modern snapshot of VS in CE again, but that name caught me of guard. I thought MS has released previews for VS 2018. Maybe consider something like MSVC 2017 (trunk) to be similar to other compilers or just MSVC (latest preview).

**Comment by mattgodbolt** [comment]
Thanks; I have no strong opinion on the name. Trunk would imply I was updating it regularly, which I'm not. (Latest preview) seems most appropriate, but is very long. I'll.see what fits

**Comment by ojeda** [comment]
My 2 cents: I would avoid using the "year" numbers (like 2017), since there are many actual IDE and compiler versions for each of those. Instead, I would use the actual IDE version (like 15.7.4). It is also what Microsoft uses in the installer and in their blog (e.g. https://blogs.msdn.microsoft.com/vcblog/2018/06/26/new-experimental-code-analysis-features-in-visual-studio-2017-15-8-preview-3/).

There is also the "Visual C++" version and the actual "cl" compiler version, but I would say those are harder to remember/track. Sadly, this would imply avoiding to use the "MSVC" name to avoid confusion about what the version is referring to. Using simply "VS" would be simpler (is there anymore a standalone "Visual C++" product?).

The "year" versions (like 2017) could be kept for the "group title", to have the best of both worlds. However, another idea is re-organizing the groups and make it like the rest of the compilers: i.e. group by arch/compiler, instead of by version.

Joining both ideas, the menu could look like this (not sure what is the minor version of VS 2015 U3; the other two are the latest available)
  * VS x86-64
    - x86-64 VS 14.?
    - x86-64 VS 15.7.4
    - x86-64 VS 15.8 Preview 3
  * VS x86
    - x86 VS 14.?
    - x86 VS 15.7.4 
    - x86 VS 15.8 Preview 3
  * VS ARM
    - ARM VS 14.?
    - ARM VS 15.7.4
    - ARM VS 15.8 Preview 3

Also note that the next "major" Visual Studio will be 2019, version 16 (there won't be a 2018).

**Comment by mattgodbolt** [comment]
Wondering if @ubsan has any thoughts (or can ask around to see what the official line might be).

**Comment by ubsan** [comment]
In my configuration files I call it VC (as in Visual C++) 15.x.y, since cl is basically just the driver.

**Comment by rlabrecque** [comment]
I'd enjoy seeing this updated too. Even "MSVC 2017 RTW" isn't super clear at this point. I'd also rather the group be called MSVC 2017, then "MSVC 15.0.0 (RTW)", "MSVC 15.8.0 (Preview 3)"

It's not as obvious which release the compiler belongs to, but it's something people should get more familiar with anyway. Having the group have the `2017` in the name helps with that issue though.

I'd also be happy with ojeda's version. I don't care about the non x86-64 platforms, and my use case is typically to try a couple different compilers in succession. Namely VS2015, VS2017 (RTW), VS2017 (Latest Preview)

**Comment by ubsan** [comment]
@rlabrecque The decision I've made in godbolt.ms is `x86_64 msvc 15.6` for compilers from 2017 onwards, and for 2015, `x86_64 msvc VS2015 Update 3`

**Comment by partouf** [comment]
The names have now changed and made more consistent, also to indicated whether it's a WINE or Windows compiler.
The VS 2015/2017 indication has been moved to group name.
And the Windows compilers even have the VS version in the names. So I think everything should be clear now.
